[package]
name = "memhack"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies.once_cell]
version = "1.12"

[dependencies.windows]
version = "0.38"
features = [
    "Win32_System_LibraryLoader",
    "Win32_Foundation"
]
