[package]
name = "memhack"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies.lazy_static]
version = "1.4"

[dependencies.windows]
version = "0.34"
features = [
    "Win32_System_LibraryLoader",
    "Win32_Foundation"
]
